version: '3'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      - MYSQL_DATABASE=mensajes_app
      - MYSQL_ROOT_PASSWORD=Temporal1
    ports:
      - '33066:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql